### ISSUE TITLE
Server side uptime not working for flask based apps.

### ISSUE THREAD

**Issue by Anindyadeep** [siddhantprateek/upptime-monitor#5]
@siddhantprateek Here is the code, when I am running the service. It shows this!

```go
package main

import "fmt"

func main() {
	output := ""
	chars := []int{107, 121, 97, 32, 109, 97, 107, 101, 32, 115, 97, 97, 98, 32, 98, 97, 100, 104, 105, 121, 97, 32, 46, 46, 46, 32, 46, 46, 46, 32, 107, 121, 97, 32, 99, 104, 97, 108, 32, 114, 97, 104, 97, 32, 104, 97, 105, 46, 46, 46, 46, 32, 115, 117, 110, 32, 114, 97, 104, 97, 32, 104, 117, 32, 98, 97, 110, 100, 105, 32, 104, 117, 105, 32, 104, 97, 105, 32, 116, 101, 114, 97, 32, 46, 46, 32, 104, 101, 32, 104, 101, 32, 104, 101}

	for _, c := range chars {
		output += string(c)
	}

	fmt.Println(output)
}

```

You can run this code, and you will get a error. Can you please check it.

**Comment by siddhantprateek** [comment]
### Please be advised of the following:

- **Nature of the Issue**: [Brief description of the problem]
- **Estimated Resolution Time**: Our team is diligently working on the problem, and we anticipate resolving it by [provide estimated time]. However, please note that this is an estimate, and the actual resolution time may vary.
- **Alternative Options**: [If applicable, provide any alternative options or workarounds available during this period]


We appreciate your patience and understanding as we work to address this issue promptly. If you have any urgent concerns or require further assistance, please do not hesitate to contact our support team
